### PR TITLE
remove confusing/unnecessary words and plurals

### PR DESCRIPTION
**Pull request by dabrahams**
I was confused by “compatible;” since it's not defined anywhere here I'm assuming it doesn't have special meaning.

### CODE REVIEW

**Comment by filip-sakel** [comment]
I don't understand why you think plurals are confusing, but I don't have any strong opinions about this either. As for the "a set of compatible" part, I don't think it's necessary. However, when we talked with @hborla about it, if I recall correctly, she wanted to emphasize the wrapper-composition scenario. I leave that for Holly to answer, though, in order for her to explain what exactly she means. 

Thank you for the thorough review!

**Comment by dabrahams** [comment]
> I don't understand why you think plurals are confusing

They're not, on their own, but they add complexity, which when needless, hurts comprehensibility.  And when you needlessly have _two_ plurals in the same sentence, correspondences between words often become ambiguous, when they could have been obvious due to the required agreement in plurality.  That's not happening in this sentence, yet.

As for “set of compatible,” for me, it raised questions without providing any information, FWIW.

**Comment by filip-sakel** [comment]
Ok, I see what you mean with the plurals example; we'll change that. As for the 'set of compatible' I agree with you that without any explanation this just causes more confusion. I'll speak with @hborla about it and about how to further simplify the rules.

**Comment by hborla** [comment]
Let's merge this. I don't care much about the "set of" part as long as it's still clear that there can be more than one wrapper attribute on the parameter.

**Pull request merged**
